version: '2'
services:
    pashmak-app:
        image: pashmak
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pashmak-postgresql:5432/Pashmak
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pashmak-postgresql:
        extends:
            file: postgresql.yml
            service: pashmak-postgresql
